---
collections:
  - name: cisco.ios
    source: https://galaxy.ansible.com

  - name: cisco.cml
    source: https://galaxy.ansible.com

  - name: ansible.builtin
    source: https://galaxy.ansible.com

  - name: ansible.netcommon
    source: https://galaxy.ansible.com