---
- name: Get CML Lab1 Facts
  hosts: localhost
  connetion: local
  gather_facts: no 

  tasks:
    - name: Collect Lab1 Facts
      cisco.cml.cml_lab_facts:
        host: 10.10.20.161
        user: developer
        password: C1sco12345
        lab: Lab1
      register: result

    - name: Print Facts Learned
        ansible.builtin.debug:
          var: result
