---
- name: "Configure OSPF-specific interface parameters"
  hosts: E10
  gather_facts: no

  tasks:
    - name: apply interface-specific OSPF settings
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: "{{ item.name }}"
            address_family:
              - afi: ipv4
                network:
                  point_to_point: true
      loop: "{{  interfaces }}"
      when: item.ospf_info.network_type is defined and item.ospf_info.network_type == "point_to_point"
