---
- name: get config differences and save to nvram
  hosts: all
  gather_facts: no
  
  tasks:
    - name: get config differences
      cisco.ios.ios_config:
        diff_against: startup
        #diff_ignore_lines:
        #  - ntp clock .*

    - name: write config to nvram if modified
      cisco.ios.ios_config:
        save_when: modified

    - name: get config differences again
      cisco.ios.ios_config:
        diff_against: startup
        #diff_ignore_lines:
        #  - ntp clock .*
