hostname: R1
mgmt_intf_name: &Mgmt_intf_name GigabitEthernet0/0
mgmt_intf_ipv4addr: &Mgmt_ipv4_addr 10.10.20.221 
mgmt_intf_ipv4mask: &Mgmt_ipv4_mask 255.255.255.0
mgmt_intf_ipv4cidr: &Mgmt_ipv4_cidr 10.10.20.221/24
mgmt_intf_next_hop: 10.10.20.254
ospfv2_router_id: 10.255.254.1
ospfv2_non_passive_ints:
  - GigabitEthernet0/3
  - GigabitEthernet0/2
ospfv2_networks:
  - address: 10.0.0.0
    wildcard_bits: 0.255.255.255
    area: '0'
  - address: 101.255.255.244
    wildcard_bits: 0.0.0.3
    area: '0'
#ospf2_autocost_refbandwidth: 10000
ospfv2_process_id: 2
interfaces:
  - name: *Mgmt_intf_name
    speed: 1000
    duplex: full
    description: Management Interface 
    enabled: true
    l3_info:
      ipv4address: *Mgmt_ipv4_cidr
  - name: GigabitEthernet0/1
    speed: 1000
    duplex: full
    description: UPLINK TO ISP1
    enabled: true
    l3_info:
      ipv4address: 101.255.255.246/30
  - name: GigabitEthernet0/2
    speed: 1000
    duplex: full
    description: R2 G0/1
    enabled: true
    l3_info:
      ipv4address: 10.255.255.241/30
    ospf_info: 
      network_type: point_to_point
  - name: GigabitEthernet0/3
    speed: 1000
    duplex: full
    description: R3 G0/1
    enabled: true
    l3_info:
      ipv4address: 10.255.255.245/30
    ospf_info: 
      network_type: point_to_point
  - name: Loopback0
    description: Loopback used for Router ID
    l3_info:
      ipv4address: 10.255.254.1/32
    ospf_info: 
      network_type: point_to_point
  - name: Loopback1
    description: User Subnet 1
    l3_info:
      ipv4address: 10.0.0.1/13
    ospf_info: 
      network_type: point_to_point
  - name: Loopback2
    description: User Subnet 2
    l3_info:
      ipv4address: 10.8.0.1/13
    ospf_info: 
      network_type: point_to_point
  - name: Loopback3
    description: User Subnet 3
    l3_info:
      ipv4address: 10.16.0.1/13
    ospf_info: 
      network_type: point_to_point
  - name: Loopback4
    description: User Subnet 4
    l3_info:
      ipv4address: 10.24.0.1/13
    ospf_info: 
      network_type: point_to_point
  