hostname: R3
mgmt_intf_name: &Mgmt_intf_name GigabitEthernet0/0
mgmt_intf_ipv4addr: &Mgmt_ipv4_addr 10.10.20.223 
mgmt_intf_ipv4mask: &Mgmt_ipv4_mask 255.255.255.0
mgmt_intf_ipv4cidr: &Mgmt_ipv4_cidr 10.10.20.223/24
mgmt_intf_next_hop: 10.10.20.254
ospfv2_router_id: 10.255.254.3
ospfv2_non_passive_ints:
  - GigabitEthernet0/1
  - GigabitEthernet0/4
ospfv2_networks:
  - address: 10.0.0.0
    wildcard_bits: 0.255.255.255
    area: '0'
interfaces:
  - name: *Mgmt_intf_name
    speed: 1000
    duplex: full
    description: Management Interface 
    enabled: true
    l3_info:
      ipv4address: *Mgmt_ipv4_cidr
  - name: GigabitEthernet0/1
    speed: 1000
    duplex: full
    description: R1 G0/3
    enabled: true
    l3_info:
      ipv4address: 10.255.255.246/30
    ospf_info: 
      network_type: point_to_point
  - name: GigabitEthernet0/4
    speed: 1000
    duplex: full
    description: R4 G0/3
    enabled: true
    l3_info:
      ipv4address: 10.255.255.253/30
    ospf_info: 
      network_type: point_to_point
  - name: Loopback0
    description: Loopback used for Router ID
    l3_info:
      ipv4address: 10.255.254.3/32
    ospf_info: 
      network_type: point_to_point
  - name: Loopback1
    description: User Subnet 1
    l3_info:
      ipv4address: 10.64.0.1/13
    ospf_info: 
      network_type: point_to_point
  - name: Loopback2
    description: User Subnet 2
    l3_info:
      ipv4address: 10.72.0.1/13
    ospf_info: 
      network_type: point_to_point
  - name: Loopback3
    description: User Subnet 3
    l3_info:
      ipv4address: 10.80.0.1/13
    ospf_info: 
      network_type: point_to_point
  - name: Loopback4
    description: User Subnet 4
    l3_info:
      ipv4address: 10.88.0.1/13
    ospf_info: 
      network_type: point_to_point
  