all:
  vars:
    ansible_user: cisco
    ansible_password: cisco
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
  children:
    isps:
      children:
        isp1:
          vars:
            bgp_as: 1
          hosts:
            10.10.20.211:
              vars:
                ansible_host: ISP1
        isp2:
          vars:
            bgp_as: 2
          hosts:
            10.10.20.212:
              vars: 
                ansible_host: ISP2
        isp3: 
          vars:
            bgp_as: 3
          hosts:
            10.10.20.213:
              vars:
                ansible_host: ISP3
        isp4:
          vars:
            bgp_as: 4
          hosts:
            10.10.20.214:
              vars:
                ansible_host: ISP4
    enterprise:
      children:
        E10: 
          vars:
            bgp_as: 10
          hosts:
            10.10.20.221:
              vars: 
                ansible_host: R1
            10.10.20.222:
              vars:
                ansible_host: R2
            10.10.20.223:
              vars:
                ansible_host: R3
            10.10.20.224:
              vars:
                ansible_host: R4


