---
- name: "CONFIGURE INTERFACES ON ALL ROUTERS"
  hosts: all
  gather_facts: no 

  tasks:
    - name: Configure base interface settings
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ item.name }}"
          description: "{{ item.description }}"
          speed: "{{ item.speed | default(omit) }}"
          duplex: "{{ item.duplex | default(omit) }}"
          enabled: "{{ item.enabled | default(omit) }}"
      loop: "{{ interfaces }}"
    - name: Configure IP Addresses
      cisco.ios.ios_l3_interfaces:
        config:
        - name: "{{ item.name }}"
          ipv4:
          - address: "{{ item.l3_info.ipv4address }}"
      loop: "{{ interfaces }}"
      when: item.l3_info is defined



          
        